# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '12.0'
target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for Runner
end

post_install do |installer|
  flutter_post_install(installer) if defined?(flutter_post_install)
end
